-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here

-- The default config is `vim.env.SSH_TTY and "" or "unnamedplus"`,
-- it means
-- 如果 SSH_TTY 环境变量存在 → 使用空字符串禁用系统剪贴板
-- 否则 -> 使用启用系统剪贴板
-- if vim.fn.has("wsl") == 1 then
--   vim.g.clipboard = {
--     name = "WslClipboard",
--     copy = {
--       ["+"] = "clip.exe",
--       ["*"] = "clip.exe",
--     },
--     paste = {
--       ["+"] = 'powershell.exe -c [Console]::Out.Write($(Get-Clipboard -Raw).tostring().replace("`r", ""))', -- bug: 中文字符乱码
--       ["*"] = 'powershell.exe -c [Console]::Out.Write($(Get-Clipboard -Raw).tostring().replace("`r", ""))',
--     },
--     cache_enabled = 0,
--   }
--   -- vim.g.clipbord = "win32yank"
-- end

-- vim.opt.spell = false

-- Lsp configuration for iwe
-- vim.api.nvim_create_autocmd("FileType", {
--   pattern = "markdown",
--   callback = function(args)
--     vim.lsp.start({
--       name = "iwes",
--       cmd = { "iwes" },
--       root_dir = vim.fs.root(args.buf, { ".iwe" }),
--       flags = {
--         debounce_text_changes = 500,
--       },
--     })
--   end,
-- })
